### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [knq/nginx-crowd-lua#1]
Hi,

I am trying to use your lua script to connect to my crowd server but I don't seem to get it working and I cannot see any debug output.

Would you have any suggestion for me?

NGINX (nginx-extras) running on ubuntu 12.04. Lua and Lua-spore installed.

How can I print debug information? 

Thank you very much for sharing this

Regards
Alessandro

**Comment by kenshaw** [comment]
You can use the nginx lua module's ngx.log() and the ngx.\* log level constants to log, like the following:

ngx.log(ngx.ERR, "error: could not do this")

These logs will show up in your nginx log files. If on debian by default that's in /var/log/nginx . Alternatively, you could use standard lua to write to another file.

In the original script, any errors thrown by the source will be relayed back to nginx and will be a 5XX error, and will likely show up in your /var/log/nginx/error.log file
